2025-10-17 05:42:08,061 [processing](INFO): Initializing backseat process (pilot lrauv based on marl)
2025-10-17 05:42:11,094 [Logger](CRITICAL): Uncaught exception
Traceback (most recent call last):
  File "./backseat_app/main.py", line 111, in <module>
    main()
  File "./backseat_app/main.py", line 107, in main
    backseat_app.spin()
  File "./backseat_app/main.py", line 75, in spin
    self.marl_processor.compute_new_heading()
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/processing.py", line 150, in compute_new_heading
    self.new_action = self.rl_tracking.newAction(self.target_address,agents_range,agents_pose,agents_depth,agents_timestamp)
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/utils.py", line 982, in newAction
    ranges=agents_range, # (targets, agents), first is always the current agent
NameError: name 'agents_range' is not defined
